// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAm92JVjDq0eQGKdLlqSxb25lahc-8IbgE',
    appId: '1:145362882731:web:9680c5280c37061ba527ee',
    messagingSenderId: '145362882731',
    projectId: 'edskoolflutter',
    authDomain: 'edskoolflutter.firebaseapp.com',
    storageBucket: 'edskoolflutter.appspot.com',
    measurementId: 'G-RTDV4DPL13',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAhR9-DgcEQy2zOJy4FokhP_J7kGp03kGk',
    appId: '1:145362882731:android:f9e3f67dfaf1ae79a527ee',
    messagingSenderId: '145362882731',
    projectId: 'edskoolflutter',
    storageBucket: 'edskoolflutter.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJbM7yrlMK66fBvtq0eIAZCFLPM36heC8',
    appId: '1:145362882731:ios:9b7298ba7ee66f34a527ee',
    messagingSenderId: '145362882731',
    projectId: 'edskoolflutter',
    storageBucket: 'edskoolflutter.appspot.com',
    iosBundleId: 'com.edskool.edSkool',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJbM7yrlMK66fBvtq0eIAZCFLPM36heC8',
    appId: '1:145362882731:ios:6b837f5d052dcc39a527ee',
    messagingSenderId: '145362882731',
    projectId: 'edskoolflutter',
    storageBucket: 'edskoolflutter.appspot.com',
    iosBundleId: 'com.edskool.edSkool.RunnerTests',
  );
}
